// Code generated by Slice Machine. DO NOT EDIT.

import EvidenceGrid from './EvidenceGrid/index.svelte';
import ProjectList from './ProjectList/index.svelte';
import TextSection from './TextSection/index.svelte';

export const components = {
	evidence_grid: EvidenceGrid,
	project_list: ProjectList,
	text_section: TextSection
};
