// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EvidenceDocumentDataSlicesSlice = EvidenceTitleSlice | TextSectionSlice;

/**
 * Content for evidence documents
 */
interface EvidenceDocumentData {
	/**
	 * Slice Zone field in *evidence*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: evidence.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<EvidenceDocumentDataSlicesSlice> /**
	 * Meta Title field in *evidence*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: evidence.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *evidence*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: evidence.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *evidence*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: evidence.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * evidence document from Prismic
 *
 * - **API ID**: `evidence`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EvidenceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<EvidenceDocumentData>,
	'evidence',
	Lang
>;

type HomeDocumentDataSlicesSlice = ProjectListSlice | EvidenceGridSlice | TextSectionSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomeDocumentData>,
	'home',
	Lang
>;

export type AllDocumentTypes = EvidenceDocument | HomeDocument;

/**
 * Item in *EvidenceGrid → Evidence Grid → Primary → Evidences*
 */
export interface EvidenceGridSliceDefaultPrimaryEvidencesItem {
	/**
	 * Title field in *EvidenceGrid → Evidence Grid → Primary → Evidences*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: The title of the project
	 * - **API ID Path**: evidence_grid.default.primary.evidences[].title
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	title: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Description field in *EvidenceGrid → Evidence Grid → Primary → Evidences*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The evidence description
	 * - **API ID Path**: evidence_grid.default.primary.evidences[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Status field in *EvidenceGrid → Evidence Grid → Primary → Evidences*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: The evidence status
	 * - **API ID Path**: evidence_grid.default.primary.evidences[].status
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	status: prismic.KeyTextField;
}

/**
 * Primary content in *EvidenceGrid → Evidence Grid → Primary*
 */
export interface EvidenceGridSliceDefaultPrimary {
	/**
	 * Title field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The section title
	 * - **API ID Path**: evidence_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Title Margin Bottom field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The bottom margin in rem after the title
	 * - **API ID Path**: evidence_grid.default.primary.title_margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	title_margin_bottom: prismic.NumberField;

	/**
	 * Flash Interval field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The time interval in milliseconds for random character flashing
	 * - **API ID Path**: evidence_grid.default.primary.flash_interval
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	flash_interval: prismic.NumberField;

	/**
	 * Flash Duration field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The character flash duration in milliseconds
	 * - **API ID Path**: evidence_grid.default.primary.flash_duration
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	flash_duration: prismic.NumberField;

	/**
	 * Glitch Interval field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The time interval in milliseconds for random character glitching
	 * - **API ID Path**: evidence_grid.default.primary.glitch_interval
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	glitch_interval: prismic.NumberField;

	/**
	 * Glitch Duration field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The character glitch duration in milliseconds
	 * - **API ID Path**: evidence_grid.default.primary.glitch_duration
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	glitch_duration: prismic.NumberField;

	/**
	 * Evidences field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: evidence_grid.default.primary.evidences[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	evidences: prismic.GroupField<Simplify<EvidenceGridSliceDefaultPrimaryEvidencesItem>>;

	/**
	 * Slice Margin Bottom field in *EvidenceGrid → Evidence Grid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The bottom margin for the slice in rem units
	 * - **API ID Path**: evidence_grid.default.primary.slice_margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	slice_margin_bottom: prismic.NumberField;
}

/**
 * Evidence Grid variation for EvidenceGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EvidenceGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<EvidenceGridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *EvidenceGrid*
 */
type EvidenceGridSliceVariation = EvidenceGridSliceDefault;

/**
 * EvidenceGrid Shared Slice
 *
 * - **API ID**: `evidence_grid`
 * - **Description**: EvidenceGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EvidenceGridSlice = prismic.SharedSlice<'evidence_grid', EvidenceGridSliceVariation>;

/**
 * Primary content in *EvidenceTitle → Default → Primary*
 */
export interface EvidenceTitleSliceDefaultPrimary {
	/**
	 * Evidence Title field in *EvidenceTitle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The title of the Evidence
	 * - **API ID Path**: evidence_title.default.primary.evidence_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	evidence_title: prismic.RichTextField;

	/**
	 * Title Margin Bottom field in *EvidenceTitle → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The bottom margin for the Evidence title
	 * - **API ID Path**: evidence_title.default.primary.title_margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	title_margin_bottom: prismic.NumberField;

	/**
	 * Evidence Date field in *EvidenceTitle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The date of the evidence
	 * - **API ID Path**: evidence_title.default.primary.evidence_date
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	evidence_date: prismic.RichTextField;

	/**
	 * Slice Margin Bottom field in *EvidenceTitle → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The bottom margin for the slice
	 * - **API ID Path**: evidence_title.default.primary.slice_margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	slice_margin_bottom: prismic.NumberField;
}

/**
 * Default variation for EvidenceTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EvidenceTitleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<EvidenceTitleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *EvidenceTitle*
 */
type EvidenceTitleSliceVariation = EvidenceTitleSliceDefault;

/**
 * EvidenceTitle Shared Slice
 *
 * - **API ID**: `evidence_title`
 * - **Description**: EvidenceTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EvidenceTitleSlice = prismic.SharedSlice<'evidence_title', EvidenceTitleSliceVariation>;

/**
 * Item in *ProjectList → Default → Primary → Project List*
 */
export interface ProjectListSliceDefaultPrimaryProjectListItem {
	/**
	 * Project Type field in *ProjectList → Default → Primary → Project List*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Project types
	 * - **API ID Path**: project_list.default.primary.project_list[].project_type
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	project_type: prismic.RichTextField;
}

/**
 * Primary content in *ProjectList → Default → Primary*
 */
export interface ProjectListSliceDefaultPrimary {
	/**
	 * Title field in *ProjectList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: The title for the project list
	 * - **API ID Path**: project_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Project List field in *ProjectList → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_list.default.primary.project_list[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	project_list: prismic.GroupField<Simplify<ProjectListSliceDefaultPrimaryProjectListItem>>;
}

/**
 * Default variation for ProjectList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectListSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProjectListSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ProjectList*
 */
type ProjectListSliceVariation = ProjectListSliceDefault;

/**
 * ProjectList Shared Slice
 *
 * - **API ID**: `project_list`
 * - **Description**: ProjectList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectListSlice = prismic.SharedSlice<'project_list', ProjectListSliceVariation>;

/**
 * Primary content in *TextSection → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
	/**
	 * Title field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The title of the section.
	 * - **API ID Path**: text_section.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Flash Interval field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The time interval in milliseconds for random character flashing
	 * - **API ID Path**: text_section.default.primary.flash_interval
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	flash_interval: prismic.NumberField;

	/**
	 * Flash Duration field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The character flash duration in milliseconds
	 * - **API ID Path**: text_section.default.primary.flash_duration
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	flash_duration: prismic.NumberField;

	/**
	 * Glitch Interval field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The time interval in milliseconds for random character glitching
	 * - **API ID Path**: text_section.default.primary.glitch_interval
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	glitch_interval: prismic.NumberField;

	/**
	 * Glitch Duration field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The character glitch duration in milliseconds
	 * - **API ID Path**: text_section.default.primary.glitch_duration
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	glitch_duration: prismic.NumberField;

	/**
	 * Title Margin Bottom field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The bottom margin in rem after the title
	 * - **API ID Path**: text_section.default.primary.title_margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	title_margin_bottom: prismic.NumberField;

	/**
	 * Paragraph field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The paragraph of the TextSection
	 * - **API ID Path**: text_section.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * Slice Margin Bottom field in *TextSection → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: The bottom margin for the slice in rem units
	 * - **API ID Path**: text_section.default.primary.slice_margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	slice_margin_bottom: prismic.NumberField;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSectionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextSection*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: TextSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSlice = prismic.SharedSlice<'text_section', TextSectionSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			EvidenceDocument,
			EvidenceDocumentData,
			EvidenceDocumentDataSlicesSlice,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			AllDocumentTypes,
			EvidenceGridSlice,
			EvidenceGridSliceDefaultPrimaryEvidencesItem,
			EvidenceGridSliceDefaultPrimary,
			EvidenceGridSliceVariation,
			EvidenceGridSliceDefault,
			EvidenceTitleSlice,
			EvidenceTitleSliceDefaultPrimary,
			EvidenceTitleSliceVariation,
			EvidenceTitleSliceDefault,
			ProjectListSlice,
			ProjectListSliceDefaultPrimaryProjectListItem,
			ProjectListSliceDefaultPrimary,
			ProjectListSliceVariation,
			ProjectListSliceDefault,
			TextSectionSlice,
			TextSectionSliceDefaultPrimary,
			TextSectionSliceVariation,
			TextSectionSliceDefault
		};
	}
}
